src/Entity/Artisan.php
<?php

namespace App\Entity;

use App\Repository\ArtisanRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArtisanRepository::class)
 */
class Artisan
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="artisans")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $kbis;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $AdressePro;

    /**
     * @ORM\Column(type="boolean")
     */
    private $atHome;

    /**
     * @ORM\Column(type="boolean")
     */
    private $canMove;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $activityPerimeter;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified;

    /**
     * @ORM\ManyToOne(targetEntity=ArtisansJob::class, inversedBy="artisans")
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cover_image;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $vitrineName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $vitrineDesc;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phoneNumber;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $coverName;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity=ArtisanPhotos::class, mappedBy="artisan")
     */
    private $artisanPhotos;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $zipCode;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    public function __construct()
    {
        $this->artisanPhotos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getKbis(): ?string
    {
        return $this->kbis;
    }

    public function setKbis(?string $kbis): self
    {
        $this->kbis = $kbis;

        return $this;
    }

    public function getAdressePro(): ?string
    {
        return $this->AdressePro;
    }

    public function setAdressePro(string $AdressePro): self
    {
        $this->AdressePro = $AdressePro;

        return $this;
    }

    public function getAtHome(): ?bool
    {
        return $this->atHome;
    }

    public function setAtHome(bool $atHome): self
    {
        $this->atHome = $atHome;

        return $this;
    }

    public function getCanMove(): ?bool
    {
        return $this->canMove;
    }

    public function setCanMove(bool $canMove): self
    {
        $this->canMove = $canMove;

        return $this;
    }

    public function getActivityPerimeter(): ?int
    {
        return $this->activityPerimeter;
    }

    public function setActivityPerimeter(?int $activityPerimeter): self
    {
        $this->activityPerimeter = $activityPerimeter;

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getCategory(): ?ArtisansJob
    {
        return $this->category;
    }

    public function setCategory(?ArtisansJob $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->cover_image;
    }

    public function setCoverImage(string $cover_image): self
    {
        $this->cover_image = $cover_image;

        return $this;
    }

    public function getVitrineName(): ?string
    {
        return $this->vitrineName;
    }

    public function setVitrineName(string $vitrineName): self
    {
        $this->vitrineName = $vitrineName;

        return $this;
    }

    public function getVitrineDesc(): ?string
    {
        return $this->vitrineDesc;
    }

    public function setVitrineDesc(string $vitrineDesc): self
    {
        $this->vitrineDesc = $vitrineDesc;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    public function getCoverName(): ?string
    {
        return $this->coverName;
    }

    public function setCoverName(string $coverName): self
    {
        $this->coverName = $coverName;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection|ArtisanPhotos[]
     */
    public function getArtisanPhotos(): Collection
    {
        return $this->artisanPhotos;
    }

    public function addArtisanPhoto(ArtisanPhotos $artisanPhoto): self
    {
        if (!$this->artisanPhotos->contains($artisanPhoto)) {
            $this->artisanPhotos[] = $artisanPhoto;
            $artisanPhoto->setArtisan($this);
        }

        return $this;
    }

    public function removeArtisanPhoto(ArtisanPhotos $artisanPhoto): self
    {
        if ($this->artisanPhotos->removeElement($artisanPhoto)) {
            // set the owning side to null (unless already changed)
            if ($artisanPhoto->getArtisan() === $this) {
                $artisanPhoto->setArtisan(null);
            }
        }

        return $this;
    }

    public function __toString(): string {
        return $this->getVitrineName();
    }

    public function getZipCode(): ?string
    {
        return $this->zipCode;
    }

    public function setZipCode(string $zipCode): self
    {
        $this->zipCode = $zipCode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Assert\Length(min="8", minMessage="Votre mot de passe doit faire plus de 8 caractères")
     */
    private $password;
    /**
     * @ORM\Column(type="string", length=16)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=16)
     */
    private $lastName;

    /**
     * @ORM\Column(type="date")
     */
    private $registerDate;

    /**
     * @ORM\Column(type="date")
     */
    private $birthDate;

    /**
     * @ORM\OneToMany(targetEntity=Articles::class, mappedBy="author")
     */
    private $articles;

    /**
     * @ORM\OneToMany(targetEntity=Artisan::class, mappedBy="user")
     */
    private $artisans;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isPro;

    /**
     * @ORM\OneToOne(targetEntity=UserSettings::class, mappedBy="user", cascade={"persist", "remove"})
     */
    private $userSettings;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getRegisterDate(): ?\DateTimeInterface
    {
        return $this->registerDate;
    }

    public function setRegisterDate(\DateTimeInterface $registerDate): self
    {
        $this->registerDate = $registerDate;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birthDate;
    }

    public function setBirthDate(\DateTimeInterface $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    /**
     * @return Collection|Articles[]
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Articles $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles[] = $article;
            $article->setAuthor($this);
        }

        return $this;
    }

    public function removeArticle(Articles $article): self
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getAuthor() === $this) {
                $article->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Artisan[]
     */
    public function getArtisans(): Collection
    {
        return $this->artisans;
    }

    public function addArtisan(Artisan $artisan): self
    {
        if (!$this->artisans->contains($artisan)) {
            $this->artisans[] = $artisan;
            $artisan->setUser($this);
        }

        return $this;
    }

    public function removeArtisan(Artisan $artisan): self
    {
        if ($this->artisans->removeElement($artisan)) {
            // set the owning side to null (unless already changed)
            if ($artisan->getUser() === $this) {
                $artisan->setUser(null);
            }
        }

        return $this;
    }

    public function __toString(): string {

        return $this->getUsername();

    }

    public function getIsPro(): ?bool
    {
        return $this->isPro;
    }

    public function setIsPro(bool $isPro): self
    {
        $this->isPro = $isPro;

        return $this;
    }

    public function getUserSettings(): ?UserSettings
    {
        return $this->userSettings;
    }

    public function setUserSettings(UserSettings $userSettings): self
    {
        // set the owning side of the relation if necessary
        if ($userSettings->getUser() !== $this) {
            $userSettings->setUser($this);
        }

        $this->userSettings = $userSettings;

        return $this;
    }

}

src/Controller/Admin/Artisans/ArtisanCrudController.php
<?php

namespace App\Controller\Admin\Artisans;

use App\Entity\Artisan;
use App\Entity\User;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Context\AdminContext;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\BooleanField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IntegerField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextareaField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use EasyCorp\Bundle\EasyAdminBundle\Router\CrudUrlGenerator;

class ArtisanCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Artisan::class;
    }


    public function configureFields(string $pageName): iterable
    {
        return [
            AssociationField::new('user', 'Utilisateur'),
            TextField::new('vitrineName', 'Nom de la vitrine'),
            TextareaField::new('vitrineDesc', 'Description de la vitrine'),
            AssociationField::new('category', 'Catégorie'),
            TextField::new('kbis', 'KBIS'),
            BooleanField::new('isVerified', 'Vérifié'),
            BooleanField::new('atHome', 'Exerce à domicile'),
            BooleanField::new('canMove', 'Se déplace'),
            IntegerField::new('activityPerimeter', 'Périmètre de déplacement (km)'),
        ];
    }

    public function configureActions(Actions $actions): Actions
    {

        $validArtisan = Action::new('validArtisan',
            'Valider le profil',
            'fas fa-check')
            ->linkToCrudAction('validArtisan')
            ->displayIf(function ($entity) {
                return !$entity->getIsVerified();
            });


        return $actions
            ->add(Crud::PAGE_INDEX, $validArtisan)
            ->disable(Action::NEW)
            ->update(Crud::PAGE_INDEX, Action::DELETE, function (Action $action) {
                return $action->setLabel('Supprimer');
            })
            ->update(Crud::PAGE_INDEX, Action::EDIT, function (Action $action) {
                return $action->setLabel('Modifier');
            });
    }

    public function validArtisan(AdminContext $context){

        $id = $context->getRequest()->query->get('entityId');
        $artisan = $this->getDoctrine()->getRepository(Artisan::class)->find($id);
        $user = $this->getDoctrine()->getRepository(User::class)->find($artisan->getUser()->getId());

        $artisan->setIsVerified(true);
        $user->setIsPro(true);
        $this->persistEntity($this->get('doctrine')->getManagerForClass($context->getEntity()->getFqcn()), $artisan);
        $this->persistEntity($this->get('doctrine')->getManagerForClass($context->getEntity()->getFqcn()), $user);

        $this->addFlash('success', 'Le profil pro a bien été validé. Sa vitrine sera désormais accessible publiquement.');

        return $this->redirect($this->get(CrudUrlGenerator::class)->build()->setAction(Action::INDEX)->generateUrl());

    }

}

src/Controller/Admin/Artisans/ArtisansJobCrudController.php
<?php

namespace App\Controller\Admin\Artisans;

use App\Entity\ArtisansJob;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class ArtisansJobCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return ArtisansJob::class;
    }


    public function configureFields(string $pageName): iterable
    {
        return [
            TextField::new('name'),
        ];
    }

    public function configureActions(Actions $actions): Actions
    {
        return $actions
            ->update(Crud::PAGE_INDEX, Action::NEW, function (Action $action) {
                return $action->setLabel('Créer un métier');
            })
            ->update(Crud::PAGE_INDEX, Action::DELETE, function (Action $action) {
                return $action->setLabel('Supprimer');
            })
            ->update(Crud::PAGE_INDEX, Action::EDIT, function (Action $action) {
                return $action->setLabel('Modifier');
            });
    }

}

templates/artisan/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ site_name }} : {{ artisan.user.firstName }} {{ artisan.user.lastName }}{% endblock %}

{% block body %}

    <div class="artisan-top" style="background-image: url({{ asset('assets/upload/artisans/' ~ artisan.coverName) }});">

        <div class="center-top">
        <h1>{{ artisan.vitrineName }}</h1>
            <h2>{{ artisan.category.name }}</h2>
        </div>

    </div>
<div class="page-content">

    <div class="artisan-container">

    <div class="artisan-container--leftpart">

        <div class="artisan-info-box w-100 bdr-10">

            <div class="artisan-profile-pic" style="background-image: url({{ asset('assets/upload/profile_pics/' ~ artisan.user.userSettings.imageName) }});"></div>

            <div class="artisan-info-box--content">
                <h2>À propos</h2>
                <h3 class="artisan-location">{{ artisan.user.firstName }} {{ artisan.user.lastName }}</h3>
                <h2 class="artisan-location">Localisation : Paris - 75019</h2>
                <p>{{ artisan.vitrineDesc }}</p>
                <div class="artisan-taglist">
                    <span>{{ artisan.category.name }}</span>
                </div>
            </div>
        </div>


    </div>


    <div class="artisan-container--rightpart">

        <div class="user-actions-list">
            <button class="user-artisans-actions"><i class="fi-rr-user-time"></i> Prendre rendez-vous</button>
            <button class="user-artisans-actions"><i class="fi-rr-list-check"></i> Voir les prestations et les prix</button>
        </div>

        <h1 style="margin-top: 30px;">Contact</h1>
        <div class="contact-artisan">

            <div class="proaddress-infos--box bdr-10 w-100">
                <div class="box-content">
                    <div class="rounded-bgr-icon primary">
                        <i class="fi-rr-envelope"></i>
                    </div>
                    <span style="color: #A6DCEF">Adresse mail :</span>
                    <span style="color: #A6DCEF">{{ artisan.user.username }}</span>
                </div>
            </div>

            <div class="proaddress-infos--box bdr-10 w-100">
                <div class="box-content">
                    <div class="rounded-bgr-icon primary">
                        <i class="fi-rr-smartphone"></i>
                    </div>
                    <span style="color: #A6DCEF">Téléphone :</span>
                    <span style="color: #A6DCEF">{{ artisan.phoneNumber }}</span>
                </div>
            </div>

        </div>

    </div>


    </div>



    <h1 style="margin-top: 30px">Localisation et périmètre d'activité</h1>

    <div class="proaddress-infos w-100">
        <div style="display: flex; flex-direction: column; width: 49%;">
        {% if artisan.atHome %}
            <div class="proaddress-infos--box w-100 bdr-10">
                <div class="box-content">
                    <div class="rounded-bgr-icon success">
                        <i class="fi-rr-check"></i>
                    </div>
                    <span style="color: #71e5ad">Le prestataire exerce à domicile</span>
                </div>
            </div>
        {% else %}
            <div class="proaddress-infos--box w-100 bdr-10">
                <div class="box-content">
                    <div class="rounded-bgr-icon danger">
                        <i class="fi-rr-cross-small"></i>
                    </div>
                    <span style="color: #ec7373">Le prestataire n'exerce pas à domicile</span>
                </div>
            </div>
        {% endif %}
        {% if artisan.canMove %}
            <div class="proaddress-infos--box w-100 bdr-10">
                <div class="box-content">
                    <div class="rounded-bgr-icon success">
                        <i class="fi-rr-check"></i>
                    </div>
                    <span style="color: #71e5ad">Le prestataire peut se déplacer à : {{ artisan.activityPerimeter }} km</span>
                </div>
            </div>
        {% else %}
            <div class="proaddress-infos--box w-100 bdr-10">
                <div class="box-content">
                    <div class="rounded-bgr-icon danger">
                        <i class="fi-rr-cross-small"></i>
                    </div>
                    <span style="color: #ec7373">Le prestataire ne se déplace pas</span>
                </div>
            </div>
        {% endif %}
        </div>
        <div onload="initialize()" id="map" style="width: 50%; height: 300px; border-radius: 10px" data-can-move="{{ artisan.canMove }}" data-activity-perimeter="{{ artisan.activityPerimeter }}"></div>
        <div id="floating-panel">
            <input id="address" type="textbox" value="{{ artisan.adressePro }}" hidden>
        </div>
    </div>





    <h1 style="margin-top: 30px">Book photo</h1>
    <div class="book-photo">

        {% for photos in artisan.getArtisanPhotos|reverse %}
            {% if photos.valid %}
            <div class="photo-box" style="background-image: url({{ asset('assets/upload/book_photo/' ~ photos.imageName) }});"></div>
            {% endif %}
        {% endfor %}

        {% for i in 0..10 %}
        {% endfor %}

    </div>

</div>
{% endblock %}

{% block javascripts %}

    <script src="https://maps.googleapis.com/maps/api/js?key={{ google_api_key }}&callback=initialize&libraries=&v=weekly" async></script>

    <script>
        let geocoder;
        let map;

        function initialize() {
            geocoder = new google.maps.Geocoder();
            var latlng = new google.maps.LatLng(-34.397, 150.644);
            var mapOptions = {
                zoom: 10,
                center: latlng
            }
            map = new google.maps.Map(document.getElementById('map'), mapOptions);
            codeAddress();
        }

        function codeAddress() {

            var address = document.getElementById('address').value;
            var carte = document.querySelector('#map');
            var canMove = carte.dataset.canMove;
            var activityPerimeter = carte.dataset.activityPerimeter

            geocoder.geocode( { 'address': address}, function(results, status) {
                if (status == 'OK') {
                    map.setCenter(results[0].geometry.location);
                    var marker = new google.maps.Marker({
                        map: map,
                        position: results[0].geometry.location
                    });

                    if(canMove){
                        var circle = new google.maps.Circle({
                            map: map,
                            radius: activityPerimeter * 1000,    // converting km from activityPerimeter to meters
                            fillColor: '#fc4040',
                            strokeWeight: 3,
                            strokeColor: '#bf0000'
                        });
                    }

                    circle.bindTo('center', marker, 'position');
                } else {
                    alert('Geocode was not successful for the following reason: ' + status);
                }
            });
        }
    </script>

{% endblock %}